version: "3"
services:
  db-mysql:
    image: mysql:8.0
    container_name: db-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"